### ISSUE TITLE
Issues on Mobile

### ISSUE THREAD

**Issue by Blackglade** [justvanrossum/nabla#65]
I can't seem to get this font to work for me on mobile devices and I'm not sure what I'm doing wrong. Both google fonts + your website is able to display it fine on mobile, but I simply get black text.

Here is my css:

```css
@import url('https://fonts.googleapis.com/css2?family=Nabla:EDPT,EHLT@150,12');

#name {
  font-family: 'Nabla', Helvetica, sans-serif;
  font-variation-settings: "EDPT" 150, "EHLT" 12;
  font-palette: --Nabla;
}

@font-palette-values --Nabla {
	font-family: 'Nabla';
	base-palette: 1;
}
```
All I get is this:

```html
<h1 id="name">Text Text</h1>
`````````````
![Screenshot](https://github.com/justvanrossum/nabla/assets/6363077/24eead9d-6112-4196-af3a-b55f7c241162)

Any idea what I am doing wrong?
